In [1]:
# ==========================================
# STEP 1 - Import Libraries
# ==========================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [2]:
# ==========================================
# STEP 2 - Load Dataset
# ==========================================

df = pd.read_csv("../data/Customer360Insights.csv")

df.head()

,SessionStart,CustomerID,FullName,Gender,Age,CreditScore,MonthlyIncome,Country,State,City,Category,Product,Cost,Price,Quantity,CampaignSchema,CartAdditionTime,OrderConfirmation,OrderConfirmationTime,PaymentMethod,SessionEnd,OrderReturn,ReturnReason
0,2019-01-01 02:42:00,1001,Brittany Franklin,Male,57,780,7591,China,Guangdong,Dongguan,electronics,table fan,30,50,4,Instagram-ads,2019-01-01 02:49:00,True,2019-01-01 03:02:00,Cash On Delivery,2019-01-01 02:53:00,False,NaN
1,2019-01-02 20:35:00,1002,Scott Stewart,Female,69,746,3912,China,Shandong,Yantai,fashion,dress,50,80,6,Google-ads,2019-01-02 20:50:00,True,2019-01-02 20:58:00,Debit Card,2019-01-02 20:54:00,False,NaN
2,2019-01-04 03:11:00,1003,Elizabeth Fowler,Female,21,772,7460,UK,England,Birmingham,toys,plush toy,12,20,2,Facebook-ads,2019-01-04 03:30:00,True,2019-01-04 03:40:00,Cash On Delivery,2019-01-04 03:35:00,False,NaN
3,2019-01-05 09:01:00,1004,Julian Wall,Female,67,631,4765,UK,England,Birmingham,toys,plush toy,12,20,2,Twitter-ads,2019-01-05 09:17:00,True,2019-01-05 09:26:00,Cash On Delivery,2019-01-05 09:20:00,False,NaN
4,2019-01-05 13:35:00,1005,James Simmons,Male,57,630,3268,China,Shandong,Yantai,fashion,shoes,60,100,6,Billboard-QR code,2019-01-05 13:40:00,True,2019-01-05 13:52:00,Debit Card,2019-01-05 13:42:00,False,NaN

In [3]:
# ==========================================
# STEP 3 - Check Data Types
# ==========================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SessionStart           2000 non-null   str
 1   CustomerID             2000 non-null   int64
 2   FullName               2000 non-null   str
 3   Gender                 2000 non-null   str
 4   Age                    2000 non-null   int64
 5   CreditScore            2000 non-null   int64
 6   MonthlyIncome          2000 non-null   int64
 7   Country                2000 non-null   str
 8   State                  2000 non-null   str
 9   City                   2000 non-null   str
 10  Category               2000 non-null   str
 11  Product                2000 non-null   str
 12  Cost                   2000 non-null   int64
 13  Price                  2000 non-null   int64
 14  Quantity               2000 non-null   int64
 15  CampaignSchema         2000 non-null   str
 16  CartAdditionTime       2000 non-null   str
 17  OrderConfirmation      2000 non-null   bool
 18  OrderConfirmationTime  1700 non-null   str
 19  PaymentMethod          1700 non-null   str
 20  SessionEnd             2000 non-null   str
 21  OrderReturn            1700 non-null   object
 22  ReturnReason           236 non-null    str
dtypes: bool(1), int64(7), object(1), str(14)
memory usage: 345.8+ KB

In [4]:
# ==========================================
# STEP 4 - Convert Datetime
# ==========================================

datetime_columns = [
    "SessionStart",
    "CartAdditionTime",
    "OrderConfirmationTime",
    "SessionEnd"
]

for col in datetime_columns:
    df[col] = pd.to_datetime(df[col])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SessionStart           2000 non-null   datetime64[us]
 1   CustomerID             2000 non-null   int64
 2   FullName               2000 non-null   str
 3   Gender                 2000 non-null   str
 4   Age                    2000 non-null   int64
 5   CreditScore            2000 non-null   int64
 6   MonthlyIncome          2000 non-null   int64
 7   Country                2000 non-null   str
 8   State                  2000 non-null   str
 9   City                   2000 non-null   str
 10  Category               2000 non-null   str
 11  Product                2000 non-null   str
 12  Cost                   2000 non-null   int64
 13  Price                  2000 non-null   int64
 14  Quantity               2000 non-null   int64
 15  CampaignSchema         2000 non-null   str
 16  CartAdditionTime       2000 non-null   datetime64[us]
 17  OrderConfirmation      2000 non-null   bool
 18  OrderConfirmationTime  1700 non-null   datetime64[us]
 19  PaymentMethod          1700 non-null   str
 20  SessionEnd             2000 non-null   datetime64[us]
 21  OrderReturn            1700 non-null   object
 22  ReturnReason           236 non-null    str
dtypes: bool(1), datetime64[us](4), int64(7), object(1), str(10)
memory usage: 345.8+ KB

In [5]:
# ==========================================
# STEP 5 - Missing Values
# ==========================================

missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Percent": round(df.isnull().mean() * 100,2)
})

missing[missing["Missing"] > 0]

                       Missing  Percent
OrderConfirmationTime      300     15.0
PaymentMethod              300     15.0
OrderReturn                300     15.0
ReturnReason              1764     88.2

In [6]:
# ==========================================
# STEP 6 - Session Features
# ==========================================

df["SessionHour"] = df["SessionStart"].dt.hour

df["SessionDay"] = df["SessionStart"].dt.day

df["SessionMonth"] = df["SessionStart"].dt.month

df["Weekday"] = df["SessionStart"].dt.day_name()

In [7]:
# ==========================================
# STEP 7 - Total Amount
# ==========================================

df["TotalAmount"] = df["Price"] * df["Quantity"]

df[["Price","Quantity","TotalAmount"]].head()

   Price  Quantity  TotalAmount
0     50         4          200
1     80         6          480
2     20         2           40
3     20         2           40
4    100         6          600

In [8]:
# ==========================================
# STEP 8 - Profit
# ==========================================

df["Profit"] = df["Price"] - df["Cost"]

df[["Cost","Price","Profit"]].head()

   Cost  Price  Profit
0    30     50      20
1    50     80      30
2    12     20       8
3    12     20       8
4    60    100      40

In [9]:
# ==========================================
# STEP 9 - Check New Columns
# ==========================================

df.columns

Index(['SessionStart', 'CustomerID', 'FullName', 'Gender', 'Age', 'CreditScore', 'MonthlyIncome', 'Country', 'State', 'City', 'Category', 'Product', 'Cost', 'Price', 'Quantity', 'CampaignSchema ',
       'CartAdditionTime', 'OrderConfirmation', 'OrderConfirmationTime', 'PaymentMethod', 'SessionEnd', 'OrderReturn', 'ReturnReason', 'SessionHour', 'SessionDay', 'SessionMonth', 'Weekday',
       'TotalAmount', 'Profit'],
      dtype='str')

In [10]:
# ==========================================
# STEP 10 - Remove Unnecessary Columns
# ==========================================

drop_columns = [
    "CustomerID",
    "FullName"
]

df = df.drop(columns=drop_columns)

df.head()

,SessionStart,Gender,Age,CreditScore,MonthlyIncome,Country,State,City,Category,Product,Cost,Price,Quantity,CampaignSchema,CartAdditionTime,OrderConfirmation,OrderConfirmationTime,PaymentMethod,SessionEnd,OrderReturn,ReturnReason,SessionHour,SessionDay,SessionMonth,Weekday,TotalAmount,Profit
0,2019-01-01 02:42:00,Male,57,780,7591,China,Guangdong,Dongguan,electronics,table fan,30,50,4,Instagram-ads,2019-01-01 02:49:00,True,2019-01-01 03:02:00,Cash On Delivery,2019-01-01 02:53:00,False,NaN,2,1,1,Tuesday,200,20
1,2019-01-02 20:35:00,Female,69,746,3912,China,Shandong,Yantai,fashion,dress,50,80,6,Google-ads,2019-01-02 20:50:00,True,2019-01-02 20:58:00,Debit Card,2019-01-02 20:54:00,False,NaN,20,2,1,Wednesday,480,30
2,2019-01-04 03:11:00,Female,21,772,7460,UK,England,Birmingham,toys,plush toy,12,20,2,Facebook-ads,2019-01-04 03:30:00,True,2019-01-04 03:40:00,Cash On Delivery,2019-01-04 03:35:00,False,NaN,3,4,1,Friday,40,8
3,2019-01-05 09:01:00,Female,67,631,4765,UK,England,Birmingham,toys,plush toy,12,20,2,Twitter-ads,2019-01-05 09:17:00,True,2019-01-05 09:26:00,Cash On Delivery,2019-01-05 09:20:00,False,NaN,9,5,1,Saturday,40,8
4,2019-01-05 13:35:00,Male,57,630,3268,China,Shandong,Yantai,fashion,shoes,60,100,6,Billboard-QR code,2019-01-05 13:40:00,True,2019-01-05 13:52:00,Debit Card,2019-01-05 13:42:00,False,NaN,13,5,1,Saturday,600,40

In [11]:
# ==========================================
# STEP 11 - Save Clean Dataset
# ==========================================

df.to_csv("../data/customer_preprocessed.csv",index=False)