In [1]:
# ==========================================
# STEP 1 - Import Libraries
# ==========================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder

pd.set_option("display.max_columns", None)

In [2]:
# ==========================================
# STEP 2 - Load Dataset
# ==========================================

df = pd.read_csv("../data/customer_preprocessed.csv")

df.head()

,SessionStart,Gender,Age,CreditScore,MonthlyIncome,Country,State,City,Category,Product,Cost,Price,Quantity,CampaignSchema,CartAdditionTime,OrderConfirmation,OrderConfirmationTime,PaymentMethod,SessionEnd,OrderReturn,ReturnReason,SessionHour,SessionDay,SessionMonth,Weekday,TotalAmount,Profit
0,2019-01-01 02:42:00,Male,57,780,7591,China,Guangdong,Dongguan,electronics,table fan,30,50,4,Instagram-ads,2019-01-01 02:49:00,True,2019-01-01 03:02:00,Cash On Delivery,2019-01-01 02:53:00,False,NaN,2,1,1,Tuesday,200,20
1,2019-01-02 20:35:00,Female,69,746,3912,China,Shandong,Yantai,fashion,dress,50,80,6,Google-ads,2019-01-02 20:50:00,True,2019-01-02 20:58:00,Debit Card,2019-01-02 20:54:00,False,NaN,20,2,1,Wednesday,480,30
2,2019-01-04 03:11:00,Female,21,772,7460,UK,England,Birmingham,toys,plush toy,12,20,2,Facebook-ads,2019-01-04 03:30:00,True,2019-01-04 03:40:00,Cash On Delivery,2019-01-04 03:35:00,False,NaN,3,4,1,Friday,40,8
3,2019-01-05 09:01:00,Female,67,631,4765,UK,England,Birmingham,toys,plush toy,12,20,2,Twitter-ads,2019-01-05 09:17:00,True,2019-01-05 09:26:00,Cash On Delivery,2019-01-05 09:20:00,False,NaN,9,5,1,Saturday,40,8
4,2019-01-05 13:35:00,Male,57,630,3268,China,Shandong,Yantai,fashion,shoes,60,100,6,Billboard-QR code,2019-01-05 13:40:00,True,2019-01-05 13:52:00,Debit Card,2019-01-05 13:42:00,False,NaN,13,5,1,Saturday,600,40

In [3]:
# ==========================================
# STEP 3 - Dataset Overview
# ==========================================

print(df.shape)

df.info()

(2000, 27)
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SessionStart           2000 non-null   str
 1   Gender                 2000 non-null   str
 2   Age                    2000 non-null   int64
 3   CreditScore            2000 non-null   int64
 4   MonthlyIncome          2000 non-null   int64
 5   Country                2000 non-null   str
 6   State                  2000 non-null   str
 7   City                   2000 non-null   str
 8   Category               2000 non-null   str
 9   Product                2000 non-null   str
 10  Cost                   2000 non-null   int64
 11  Price                  2000 non-null   int64
 12  Quantity               2000 non-null   int64
 13  CampaignSchema         2000 non-null   str
 14  CartAdditionTime       2000 non-null   str
 15  OrderConfirmation      2000 non-null   bool
 16  OrderConfirmationTime  1700 non-null   str
 17  PaymentMethod          1700 non-null   str
 18  SessionEnd             2000 non-null   str
 19  OrderReturn            1700 non-null   object
 20  ReturnReason           236 non-null    str
 21  SessionHour            2000 non-null   int64
 22  SessionDay             2000 non-null   int64
 23  SessionMonth           2000 non-null   int64
 24  Weekday                2000 non-null   str
 25  TotalAmount            2000 non-null   int64
 26  Profit                 2000 non-null   int64
dtypes: bool(1), int64(11), object(1), str(14)
memory usage: 408.3+ KB

In [4]:
# ==========================================
# STEP 4 - Select Target
# ==========================================

target = "OrderConfirmation"

In [5]:
# ==========================================
# STEP 5 - Remove Data Leakage
# ==========================================

drop_columns = [

    "OrderConfirmationTime",

    "PaymentMethod",

    "OrderReturn",

    "ReturnReason"

]

In [6]:
drop_columns += [

    "SessionStart",

    "CartAdditionTime",

    "SessionEnd"

]

In [7]:
# ==========================================
# STEP 7 - Split Feature & Target
# ==========================================

X = df.drop(columns=drop_columns + [target])

y = df[target]

In [8]:
X.head()

,Gender,Age,CreditScore,MonthlyIncome,Country,State,City,Category,Product,Cost,Price,Quantity,CampaignSchema,SessionHour,SessionDay,SessionMonth,Weekday,TotalAmount,Profit
0,Male,57,780,7591,China,Guangdong,Dongguan,electronics,table fan,30,50,4,Instagram-ads,2,1,1,Tuesday,200,20
1,Female,69,746,3912,China,Shandong,Yantai,fashion,dress,50,80,6,Google-ads,20,2,1,Wednesday,480,30
2,Female,21,772,7460,UK,England,Birmingham,toys,plush toy,12,20,2,Facebook-ads,3,4,1,Friday,40,8
3,Female,67,631,4765,UK,England,Birmingham,toys,plush toy,12,20,2,Twitter-ads,9,5,1,Saturday,40,8
4,Male,57,630,3268,China,Shandong,Yantai,fashion,shoes,60,100,6,Billboard-QR code,13,5,1,Saturday,600,40

In [9]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           2000 non-null   str
 1   Age              2000 non-null   int64
 2   CreditScore      2000 non-null   int64
 3   MonthlyIncome    2000 non-null   int64
 4   Country          2000 non-null   str
 5   State            2000 non-null   str
 6   City             2000 non-null   str
 7   Category         2000 non-null   str
 8   Product          2000 non-null   str
 9   Cost             2000 non-null   int64
 10  Price            2000 non-null   int64
 11  Quantity         2000 non-null   int64
 12  CampaignSchema   2000 non-null   str
 13  SessionHour      2000 non-null   int64
 14  SessionDay       2000 non-null   int64
 15  SessionMonth     2000 non-null   int64
 16  Weekday          2000 non-null   str
 17  TotalAmount      2000 non-null   int64
 18  Profit           2000 non-null   int64
dtypes: int64(11), str(8)
memory usage: 297.0 KB

In [10]:
# ==========================================
# STEP 9 - Find Categorical Columns
# ==========================================

categorical_columns = X.select_dtypes(include="object").columns

categorical_columns

C:\Users\PC\AppData\Local\Temp\ipykernel_9788\871788640.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include="object").columns

Index(['Gender', 'Country', 'State', 'City', 'Category', 'Product',
       'CampaignSchema ', 'Weekday'],
      dtype='str')

In [11]:
# ==========================================
# STEP 10 - One Hot Encoding
# ==========================================

encoder = OneHotEncoder(
    sparse_output=False,
    handle_unknown="ignore"
)

encoded = encoder.fit_transform(
    X[categorical_columns]
)

In [12]:
encoded_df = pd.DataFrame(

    encoded,

    columns=encoder.get_feature_names_out(categorical_columns),

    index=X.index

)

In [13]:
X = X.drop(columns=categorical_columns)

X = pd.concat(
    [X, encoded_df],
    axis=1
)

In [14]:
# ==========================================
# STEP 13 - Convert Target
# ==========================================

y = y.astype(int)

In [15]:
print(X.shape)

X.info()

X.head()

y.head()

(2000, 130)
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Columns: 130 entries, Age to Weekday_Wednesday
dtypes: float64(119), int64(11)
memory usage: 2.0 MB

0    1
1    1
2    1
3    1
4    1
Name: OrderConfirmation, dtype: int64

In [16]:
# ==========================================
# STEP 15 - Save Dataset
# ==========================================

X.to_csv("../data/X.csv", index=False)

y.to_csv("../data/y.csv", index=False)